/**
 * Localization module registry (generated by scripts/gen-loc-index.mjs; rerun after adding a module).
 */
import type { EegModule } from '../../eeg/types';

import m01 from './m01-where-before-what.json';
import m02 from './m02-the-exam.json';
import m03 from './m03-first-fork.json';
import m04 from './m04-motor-unit.json';
import m05 from './m05-roots-plexus-nerves.json';
import m06 from './m06-spinal-cord.json';
import m07 from './m07-brainstem.json';
import m08 from './m08-loops.json';
import m09 from './m09-hemispheres.json';
import m10 from './m10-everywhere.json';
import m11 from './m11-where-to-what.json';
import m12 from './m12-cases.json';

export const LOC_MODULES: EegModule[] = [
  m01, m02, m03, m04, m05, m06, m07, m08, m09, m10, m11, m12,
] as EegModule[];

export function getLocModule(id: string): EegModule | undefined {
  return LOC_MODULES.find(m => m.id === id);
}
