#!/usr/bin/env python3
"""Render public/eeg/ATTRIBUTIONS.md from src/eeg/figures.json. Run after either extractor."""
import json
from pathlib import Path

REG = Path("src/eeg/figures.json")
OUT = Path("public/eeg/ATTRIBUTIONS.md")
IMG = Path("public/eeg/figures")

AES_BOOK = ("St. Louis EK, Frey LC, eds. Electroencephalography (EEG): An Introductory Text and Atlas of "
            "Normal and Abnormal Findings in Adults, Children, and Infants. Chicago: American Epilepsy "
            "Society; 2016. https://www.ncbi.nlm.nih.gov/books/NBK390346/")

reg = json.loads(REG.read_text())
aes = [r for r in reg if r.get("source", "aes") == "aes"]
shoup = [r for r in reg if r.get("source") == "shoup"]
size = lambda rs: sum((IMG / Path(r["file"]).name).stat().st_size for r in rs) / 1e6

lines = [
    "# EEG figure attributions",
    "",
    f"{len(reg)} tracings under `public/eeg/figures/`. Every image on the site carries its credit and licence in its caption.",
    "",
    f"## American Epilepsy Society atlas ({len(aes)} figures, {size(aes):.1f} MB)",
    "",
    f"> {AES_BOOK}",
    "",
    "Licence: CC BY-NC-SA 4.0 (https://creativecommons.org/licenses/by-nc-sa/4.0/). The book states that its figures are "
    "published under the same licence and should be cited when reused. Figures carrying a separate copyright notice in the "
    "book (Mayo Foundation for Medical Education and Research) were not copied.",
    "",
    "Changes made: images were extracted from the PDF, converted to JPEG and resized to at most 1600 px wide. Captions were "
    "shortened for display; the full caption is kept in `src/eeg/figures.json`. Any derivative use of these images must carry "
    "the same licence (ShareAlike). Generated by `scripts/extract_aes_figures.py`.",
    "",
    "| Figure | Title | Credit | Book page |",
    "|---|---|---|---|",
]
lines += [f"| {r['number']} | {r['title']} | {r['credit']} | {r['page']} |" for r in aes]
lines += [
    "",
    f"## Jaime Shoup, MD, University of Louisville ({len(shoup)} figures, {size(shoup):.1f} MB)",
    "",
    "Tracings from the lecture \"Non-Epileptiform EEG Abnormalities\" (Norton Children's Neuroscience Institute, University of "
    "Louisville), reproduced with the author's permission, confirmed to the site owner on 2026-09-30. These images are **not** "
    "under a Creative Commons licence: they may be viewed on this site but not copied elsewhere without the author's consent. "
    "Slides carrying a Mayo Foundation permission line, a scanned journal figure and an unlabelled tracing were excluded. "
    "Generated by `scripts/extract_shoup_figures.py`.",
    "",
    "| Slide | Title |",
    "|---|---|",
]
lines += [f"| {r['number']} | {r['title']} |" for r in shoup]
OUT.write_text("\n".join(lines) + "\n")
print(f"attributions: {len(aes)} AES + {len(shoup)} Shoup")
